name: double-machine-learning
channels:
- pytorch
- defaults
dependencies:
- black
- cffi
- cmake
- jupyter
- matplotlib
- mkl
- nb_conda
- numpy
- pytorch
- pyyaml
- scikit-image
- scikit-learn
- scipy
- seaborn
- setuptools
- torchvision
- tqdm
